namespace: cybersafekids

resources:
  - ../../base

images:
  - name: registry.cyber-safekids.com/cybersafekids/backend
    newTag: v1.0.3
  - name: registry.cyber-safekids.com/cybersafekids/frontend
    newTag: v1.0.3
